apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rrelayer.fullname" . }}-config
  labels:
    {{- include "rrelayer.labels" . | nindent 4 }}
data:
  rrelayer.yaml: |
    name: first-rrelayer
    description: 'my first rrelayer'
    api_config:
      port: 3000
